### ISSUE TITLE
[unsupport] not support on vel 3.2.0-SNAPSHOT (git-19abb909-b265)

### ISSUE THREAD

**Issue by shenjackyuanjie** [The-Cat-Town-Craft/Auto-World-Map#1]
```
[13:13:51 ERROR] [dev.simplix.protocolize.velocity.providers.VelocityProtocolRegistrationProvider]: Exception while registering packet top.catowncraft.autoworldmap.common.packet.ClientboundSetDefaultSpawnPositionPacket
java.lang.reflect.InvocationTargetException: null
        at jdk.internal.reflect.GeneratedMethodAccessor11.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at dev.simplix.protocolize.velocity.providers.VelocityProtocolRegistrationProvider.doRegisterPacket(VelocityProtocolRegistrationProvider.java:122) ~[?:?]
        at dev.simplix.protocolize.velocity.providers.VelocityProtocolRegistrationProvider.registerPacket(VelocityProtocolRegistrationProvider.java:107) ~[?:?]
        at top.catowncraft.autoworldmap.AutoWorldMapVelocity.onProxyInitialization(AutoWorldMapVelocity.java:42) ~[?:?]
        at top.catowncraft.autoworldmap.Lmbda$2.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.2.0-SNAPSHOT-265.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity-3.2.0-SNAPSHOT-265.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity-3.2.0-SNAPSHOT-265.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalArgumentException: Next mapping version (1.19.1) should be lower then current (1.19.1)
        at com.velocitypowered.proxy.protocol.StateRegistry$PacketRegistry.register(StateRegistry.java:498) ~[velocity-3.2.0-SNAPSHOT-265.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        ... 13 more
```

**Comment by Hendrix-Shen** [comment]
试一下 [1.3.21+f14e7a5](https://github.com/The-Cat-Town-Craft/Auto-World-Map/releases/tag/dev-21)

**Comment by shenjackyuanjie** [comment]
好欸！
这就去试试

**Comment by shenjackyuanjie** [comment]
Fixed
